name: Manual Approval Before Merge 1

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  require-manual-approval:
    name: Wait for Manual Approval
    runs-on: ubuntu-latest
    steps:
      - name: Approved ✅
        run: echo "Manual approval granted. Ready to merge."
