name: Manual Approval Before Merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  check:
    name: Accept Change
    runs-on: ubuntu-latest
    outputs:
      requires-approval: ${{ steps.check.outputs.approval }}
      artifact-path: ${{ steps.save.outputs.path }}
    steps:
      - id: check
        run: echo "approval=true" >> $GITHUB_OUTPUT

      - id: save
        run: echo "path=build/output.zip" >> $GITHUB_OUTPUT && exit 1

  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: echo ${{ needs.check.outputs.requires-approval }}
      - run: echo "Deploying from path ${{ needs.check.outputs.artifact-path }}"

  require-manual-approval:
    name: Wait for Manual Approval
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.requires-approval == 'true'
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
    steps:
      - name: Approved ✅
        run: echo "Manual approval granted. Ready to merge."
