name: Manual Approval Before Merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  require-manual-approval:
    name: Wait for Manual Approval
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
    steps:
      - name: Approved ✅
        run: echo "Manual approval granted. Ready to merge."
