name: Manual Approval Before Merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  check:
    name: Accept Change
    runs-on: ubuntu-latest
    outputs:
      requires_approval: ${{ steps.set-output.outputs.requires_approval }}
    steps:
      - name: Approved ✅
        run: echo "requires_approval=true" >> $GITHUB_OUTPUT

  require-manual-approval:
    name: Wait for Manual Approval
    runs-on: ubuntu-latest
    needs: check
    if: needs.check-condition.outputs.requires_approval == 'true'
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
    steps:
      - name: Approved ✅
        run: echo "Manual approval granted. Ready to merge."
  
  accept:
    name: Accept Change
    runs-on: ubuntu-latest
    needs: require-manual-approval
    steps:
      - name: Approved ✅
        run: echo "Manual approval granted. Ready to merge."

